name: lzk
favicon: null
layout_spectrum: 0.25735
typography_spectrum: 0.61678
title: lzk arquitetura
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#969696'
    - '#636363'
    - '#e30013'
  brandStrength: 0.42284745490178466
  lightness: 0.9164966610260308
  saturation: 0.4066418583970517
  rhythmicContrast: 0.8175502181984484
purpose: []
